//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NullCheckCsAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NullCheckCsAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-nullable types does not require null-checks.
        /// </summary>
        internal static string NullCheckDescription {
            get {
                return ResourceManager.GetString("NullCheckDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has non-nullable type and doesn&apos;t require a null-check.
        /// </summary>
        internal static string NullCheckMessageFormat {
            get {
                return ResourceManager.GetString("NullCheckMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable of non-nullable type has null-check.
        /// </summary>
        internal static string NullCheckTitle {
            get {
                return ResourceManager.GetString("NullCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null coalescing on non-nullable type is meaningless.
        /// </summary>
        internal static string NullCoalesceDescription {
            get {
                return ResourceManager.GetString("NullCoalesceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null coalescing will always evaluate to &apos;{0}&apos;.
        /// </summary>
        internal static string NullCoalesceMessageFormat {
            get {
                return ResourceManager.GetString("NullCoalesceMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null coalescing on non-nullable type.
        /// </summary>
        internal static string NullCoalesceTitle {
            get {
                return ResourceManager.GetString("NullCoalesceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null propagation on non-nullable type is meaningless.
        /// </summary>
        internal static string NullPropagationDescription {
            get {
                return ResourceManager.GetString("NullPropagationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is always not null and does not require null propagation.
        /// </summary>
        internal static string NullPropagationMessageFormat {
            get {
                return ResourceManager.GetString("NullPropagationMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null propagation on non-nullable type.
        /// </summary>
        internal static string NullPropagationTitle {
            get {
                return ResourceManager.GetString("NullPropagationTitle", resourceCulture);
            }
        }
    }
}
